### ISSUE TITLE
gitlab-runner and foobar2000 failing URL

### ISSUE THREAD

**Issue by majkinetor** [chocolatey/package-validator#243]
Not sure why this package isnt passing validation, complains about invalid URLs which are valid

- https://chocolatey.org/packages/gitlab-runner/13.4.0
- https://chocolatey.org/packages/foobar2000/1.6

**Comment by gep13** [comment]
@majkinetor thanks for raising this.  Seems like this is related to this issue:

https://github.com/chocolatey/package-validator/issues/242

As they are both failing with the same exception.

**Comment by chtof** [comment]
https://chocolatey.org/packages/cudatext/1.111.5.0
https://chocolatey.org/packages/cudatext/1.111.5.3
https://chocolatey.org/packages/cudatext/1.111.6.0
https://chocolatey.org/packages/cudatext/1.112.0.0
https://chocolatey.org/packages/cudatext/1.112.1.0
https://chocolatey.org/packages/cudatext/1.113.0.0

_The DocsUrl element in the nuspec file should be a valid Url. Please correct this More..._

But the DocsUrl is valid: https://wiki.freepascal.org/CudaText

Another point: These 7 versions are in "Verification Testing Pending", so it seems Verification Testing for this package is blocked since the check of DocsUrl fails.

**Comment by gep13** [comment]
@chtof I have re-ran all these package versions through the package-validator, and they are now correctly validating the URL's.  They should now also flow into the package-verifier queue.  Let me know if you are still having issues with them.

**Comment by gep13** [comment]
@majkinetor apologies on taking so long to get to this.

This problem has been addressed, and the gitlab-runner package is now passing validation.

It seems as though the foobar package already got through.

**Comment by gep13** [comment]
@chtof when I went to check, the cudatext packages were also passing correctly, so I don't think there is anything to do there.
