### ISSUE TITLE
Command line version?

### ISSUE THREAD

**Issue by alexdresko** [chocolatey/package-validator#88]
I'd love to have a command line version of the validator and verifier that I could integrate into my gulp builds. 

Is that a possibility? I haven't looked into either project well enough to know, and I figured it'd be a better use of my time to just ask.

**Comment by gep13** [comment]
@alexdresko thanks for reaching out!

Ultimately, the plan is for the package validator rules and logic to make their way back into the Chocolatey Command Line, so that during the execution of `choco pack` the same output will be shown to the creator of the package.  The reason that we started this work in the standalone Windows Service version was to help with the moderation back log that we have, but as I said, it will roll back into Chocolatey as well.

Hope that makes sense.

**Comment by alexdresko** [comment]
Makes perfect sense, and it's a perfect plan. Thank you for clarifying and I apologize if this has already been asked before. Well done, everyone!

**Comment by gep13** [comment]
@alexdresko not a problem at all :+1:

**Comment by ferventcoder** [comment]
Thanks!
